import { dev } from '$app/environment';

export const assetMap = {
  ballIcons: {
    berserk: dev
      ? '/assets/ball_icon_berserk.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954333/ball_x_pit/ball_icons/ball_icon_berserk.png',
    bleed: dev
      ? '/assets/ball_icon_bleed.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954334/ball_x_pit/ball_icons/ball_icon_bleed.png',
    bomb: dev
      ? '/assets/ball_icon_bomb.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954335/ball_x_pit/ball_icons/ball_icon_bomb.png',
    burn: dev
      ? '/assets/ball_icon_burn.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954336/ball_x_pit/ball_icons/ball_icon_burn.png',
    earthquake: dev
      ? '/assets/ball_icon_earthquake.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954338/ball_x_pit/ball_icons/ball_icon_earthquake.png',
    flash: dev
      ? '/assets/ball_icon_flash.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954339/ball_x_pit/ball_icons/ball_icon_flash.png',
    hemorrhage: dev
      ? '/assets/ball_icon_hemorrhage.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954343/ball_x_pit/ball_icons/ball_icon_hemorrhage.png',
    inferno: dev
      ? '/assets/ball_icon_inferno.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954346/ball_x_pit/ball_icons/ball_icon_inferno.png',
    iron: dev
      ? '/assets/ball_icon_iron.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954346/ball_x_pit/ball_icons/ball_icon_iron.png',
    nuclearBomb: dev
      ? '/assets/ball_icon_nuclear_bomb.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954357/ball_x_pit/ball_icons/ball_icon_nuclear_bomb.png',
    poison: dev
      ? '/assets/ball_icon_poison.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954359/ball_x_pit/ball_icons/ball_icon_poison.png',
    sacrifice: dev
      ? '/assets/ball_icon_sacrifice.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954361/ball_x_pit/ball_icons/ball_icon_sacrifice.png',
    shotgun: dev
      ? '/assets/ball_icon_shotgun.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954363/ball_x_pit/ball_icons/ball_icon_shotgun.png',
    wrath: dev
      ? '/assets/ball_icon_wrath.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954372/ball_x_pit/ball_icons/ball_icon_wrath.png',
    dark: dev
      ? '/assets/ball_icon_dark.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954337/ball_x_pit/ball_icons/ball_icon_dark.png',
    light: dev
      ? '/assets/ball_icon_light.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954350/ball_x_pit/ball_icons/ball_icon_light.png',
    lightning: dev
      ? '/assets/ball_icon_lightning.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954351/ball_x_pit/ball_icons/ball_icon_lightning.png',
    wind: dev
      ? '/assets/ball_icon_wind.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954372/ball_x_pit/ball_icons/ball_icon_wind.png',
    sun: dev
      ? '/assets/ball_icon_sun.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954367/ball_x_pit/ball_icons/ball_icon_sun.png',
    blizzard: dev
      ? '/assets/ball_icon_blizzard.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954334/ball_x_pit/ball_icons/ball_icon_blizzard.png',
    freeze: dev
      ? '/assets/ball_icon_freeze.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954340/ball_x_pit/ball_icons/ball_icon_freeze.png',
    freezeRay: dev
      ? '/assets/ball_icon_freeze_ray.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954340/ball_x_pit/ball_icons/ball_icon_freeze.png',
    frozenFlame: dev
      ? '/assets/ball_icon_frozen_flame.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954341/ball_x_pit/ball_icons/ball_icon_frozen_flame.png',
    glacier: dev
      ? '/assets/ball_icon_glacier.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954342/ball_x_pit/ball_icons/ball_icon_glacier.png',
    holyLaser: dev
      ? '/assets/ball_icon_holy_laser.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954344/ball_x_pit/ball_icons/ball_icon_holy_laser.png',
    laserBeam: dev
      ? '/assets/ball_icon_laser_beam.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954347/ball_x_pit/ball_icons/ball_icon_laser_beam.png',
    laserHorizontal: dev
      ? '/assets/ball_icon_laser_horizontal.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954348/ball_x_pit/ball_icons/ball_icon_laser_horizontal.png',
    laserVertical: dev
      ? '/assets/ball_icon_laser_vertical.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954349/ball_x_pit/ball_icons/ball_icon_laser_vertical.png',
    radiationBeam: dev
      ? '/assets/ball_icon_radiation_beam.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954360/ball_x_pit/ball_icons/ball_icon_radiation_beam.png',
    cell: dev
      ? '/assets/ball_icon_cell.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954336/ball_x_pit/ball_icons/ball_icon_cell.png',
    eggSac: dev
      ? '/assets/ball_icon_egg_sac.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954338/ball_x_pit/ball_icons/ball_icon_egg_sac.png',
    magma: dev
      ? '/assets/ball_icon_magma.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954354/ball_x_pit/ball_icons/ball_icon_magma.png',
    overgrowth: dev
      ? '/assets/ball_icon_overgrowth.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954358/ball_x_pit/ball_icons/ball_icon_overgrowth.png',
    sandstorm: dev
      ? '/assets/ball_icon_sandstorm.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954361/ball_x_pit/ball_icons/ball_icon_sandstorm.png',
    storm: dev
      ? '/assets/ball_icon_storm.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954365/ball_x_pit/ball_icons/ball_icon_storm.png',
    swamp: dev
      ? '/assets/ball_icon_swamp.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954367/ball_x_pit/ball_icons/ball_icon_swamp.png',
    voluptuousEggSac: dev
      ? '/assets/ball_icon_voluptuous_egg_sac.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954370/ball_x_pit/ball_icons/ball_icon_voluptuous_egg_sac.png',
    broodMother: dev
      ? '/assets/ball_icon_brood_mother.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954335/ball_x_pit/ball_icons/ball_icon_brood_mother.png',
    darkAssassin: dev
      ? '/assets/ball_icon_dark_assassin.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954336/ball_x_pit/ball_icons/ball_icon_dark_assassin.png',
    ghost: dev
      ? '/assets/ball_icon_ghost.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954341/ball_x_pit/ball_icons/ball_icon_ghost.png',
    incubus: dev
      ? '/assets/ball_icon_incubus.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954344/ball_x_pit/ball_icons/ball_icon_incubus.png',
    leech: dev
      ? '/assets/ball_icon_leech.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954349/ball_x_pit/ball_icons/ball_icon_leech.png',
    maggot: dev
      ? '/assets/ball_icon_maggot.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954353/ball_x_pit/ball_icons/ball_icon_maggot.png',
    mosquitoSwarm: dev
      ? '/assets/ball_icon_mosquito_swarm.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1761011974/ball_icon_mosquito_swarm_erfffn.png',
    mosquitoKing: dev
      ? '/assets/ball_icon_mosquito_king.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954355/ball_x_pit/ball_icons/ball_icon_mosquito_king.png',
    nosferatu: dev
      ? '/assets/ball_icon_nosferatu.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954355/ball_x_pit/ball_icons/ball_icon_nosferatu.png',
    phantom: dev
      ? '/assets/ball_icon_phantom.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954359/ball_x_pit/ball_icons/ball_icon_phantom.png',
    satan: dev
      ? '/assets/ball_icon_satan.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954362/ball_x_pit/ball_icons/ball_icon_satan.png',
    soulSucker: dev
      ? '/assets/ball_icon_soul_sucker.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954364/ball_x_pit/ball_icons/ball_icon_soul_sucker.png',
    spiderQueen: dev
      ? '/assets/ball_icon_spider_queen.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954364/ball_x_pit/ball_icons/ball_icon_spider_queen.png',
    succubus: dev
      ? '/assets/ball_icon_succubus.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954366/ball_x_pit/ball_icons/ball_icon_succubus.png',
    vampire: dev
      ? '/assets/ball_icon_vampire.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954369/ball_x_pit/ball_icons/ball_icon_vampire.png',
    vampireLord: dev
      ? '/assets/ball_icon_vampire_lord.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954369/ball_x_pit/ball_icons/ball_icon_vampire_lord.png',
    blackHole: dev
      ? '/assets/ball_icon_black_hole.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954333/ball_x_pit/ball_icons/ball_icon_black_hole.png',
    flicker: dev
      ? '/assets/ball_icon_flicker.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954339/ball_x_pit/ball_icons/ball_icon_flicker.png',
    charm: dev
      ? '/assets/ball_icon_charm.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954351/ball_x_pit/ball_icons/ball_icon_love_charm.png',
    lovestruck: dev
      ? '/assets/ball_icon_lovestruck.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954352/ball_x_pit/ball_icons/ball_icon_lovestruck.png',
    noxious: dev
      ? '/assets/ball_icon_noxious.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954356/ball_x_pit/ball_icons/ball_icon_noxious.png',
    virus: dev
      ? '/assets/ball_icon_virus.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954370/ball_x_pit/ball_icons/ball_icon_vrius.png',
    lightningRod: dev
      ? '/assets/ball_pit_lightning_rod.png'
      : 'https://res.cloudinary.com/dnmknegr2/image/upload/v1760954373/ball_x_pit/ball_icons/ball_pit_lightning_rod.png'
  }
};

export default assetMap;
