// Asset map for ball icons and pit items
export const assetMap = {
  ballIcons: {
    berserk: '/assets/ball_icon_berserk.png',
    bleed: '/assets/ball_icon_bleed.png',
    bomb: '/assets/ball_icon_bomb.png',
    burn: '/assets/ball_icon_burn.png',
    earthquake: '/assets/ball_icon_earthquake.png',
    flash: '/assets/ball_icon_flash.png',
    hemorrhage: '/assets/ball_icon_hemorrhage.png',
    inferno: '/assets/ball_icon_inferno.png',
    iron: '/assets/ball_icon_iron.png',
    nuclearBomb: '/assets/ball_icon_nuclear_bomb.png',
    poison: '/assets/ball_icon_poison.png',
    sacrifice: '/assets/ball_icon_sacrifice.png',
    shotgun: '/assets/ball_icon_shotgun.png',
    wrath: '/assets/ball_icon_wrath.png',
    dark: '/assets/ball_icon_dark.png',
    light: '/assets/ball_icon_light.png',
    lightning: '/assets/ball_icon_lightning.png',
    wind: '/assets/ball_icon_wind.png',
    sun: '/assets/ball_icon_sun.png',
    blizzard: '/assets/ball_icon_blizzard.png',
    freeze: '/assets/ball_icon_freeze.png',
    freezeRay: '/assets/ball_icon_freeze_ray.png',
    frozenFlame: '/assets/ball_icon_frozen_flame.png',
    glacier: '/assets/ball_icon_glacier.png',
    holyLaser: '/assets/ball_icon_holy_laser.png',
    laserBeam: '/assets/ball_icon_laser_beam.png',
    laserHorizontal: '/assets/ball_icon_laser_horizontal.png',
    laserVertical: '/assets/ball_icon_laser_vertical.png',
    radiationBeam: '/assets/ball_icon_radiation_beam.png',
    cell: '/assets/ball_icon_cell.png',
    eggSac: '/assets/ball_icon_egg_sac.png',
    magma: '/assets/ball_icon_magma.png',
    overgrowth: '/assets/ball_icon_overgrowth.png',
    sandstorm: '/assets/ball_icon_sandstorm.png',
    storm: '/assets/ball_icon_storm.png',
    swamp: '/assets/ball_icon_swamp.png',
    voluptuousEggSac: '/assets/ball_icon_voluptuous_egg_sac.png',
    broodMother: '/assets/ball_icon_brood_mother.png',
    darkAssassin: '/assets/ball_icon_dark_assassin.png',
    ghost: '/assets/ball_icon_ghost.png',
    incubus: '/assets/ball_icon_incubus.png',
    leech: '/assets/ball_icon_leech.png',
    maggot: '/assets/ball_icon_maggot.png',
    mosquitoKing: '/assets/ball_icon_mosquito_king.png',
    nosferatu: '/assets/ball_icon_nosferatu.png',
    phantom: '/assets/ball_icon_phantom.png',
    satan: '/assets/ball_icon_satan.png',
    soulSucker: '/assets/ball_icon_soul_sucker.png',
    spiderQueen: '/assets/ball_icon_spider_queen.png',
    succubus: '/assets/ball_icon_succubus.png',
    vampire: '/assets/ball_icon_vampire.png',
    vampireLord: '/assets/ball_icon_vampire_lord.png',
    blackHole: '/assets/ball_icon_black_hole.png',
    flicker: '/assets/ball_icon_flicker.png',
    charm: '/assets/ball_icon_love_charm.png',
    lovestruck: '/assets/ball_icon_lovestruck.png',
    noxious: '/assets/ball_icon_noxious.png',
    vrius: '/assets/ball_icon_vrius.png',
    lightningRod: '/assets/ball_pit_lightning_rod.png'
  }
};

export default assetMap;
